name: vitcalendar
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - google-api-python-client
      - google-auth-httplib2
      - google-auth-oauthlib
      - python-dotenv
